version: '3'

tasks:
  init:
    desc: Initialize local configuration file from template
    status:
      - test -f .trmnlp.yml
    cmds:
      - cp .trmnlp.yml.example .trmnlp.yml

  lint:
    desc: Run Shopify Theme Check linter on Liquid files
    cmds:
      - shopify theme check

  format:
    desc: Run Prettier formatting on source templates and configurations
    cmds:
      - npx prettier --write "src/**/*.liquid" "src/**/*.yml"

  serve:
    desc: Run local TRMNL preview server using Docker container
    env:
      APP_ENV: production
      RACK_ENV: production
    preconditions:
      - which trmnlp
    # dir: ./src
    cmds:
      - trmnlp serve -b 0.0.0.0
